### ISSUE TITLE
Breadcrumb URLS don't work if baseURL isn't root folder

### ISSUE THREAD

**Issue by ADeeds** [capnfabs/paperesque#10]
When I set baseURL in my config.toml to something like <mywebsite.com>/blog, I noticed that the breadcrumb links on an individual post that went back to the posts page stopped working. The URL was pointing to <mywebsite>/blogposts, instead of <mywebsite>/blog/posts

I think that this could be fixed by editing layouts/_default/single.html to use `<a href="{{ .CurrentSection.Type | relURL }}">{{.CurrentSection.Name}}</a>` instead of `<a href="{{ .Site.BaseURL  }}{{ .CurrentSection.Type }}">{{.CurrentSection.Name}}</a>`. I'm not able to put together a PR today, but if that would be helpful please let me know.

As someone who probably goes overboard with footnotes, I've been really enjoying the theme since I first tried it out yesterday. Thanks for creating it!

**Comment by capnfabs** [comment]
Hey @ADeeds, thanks for the report! It's a simple fix and it's also easy to test, so I'll fix it myself. 

Glad you're enjoying the footnotes! :)

**Comment by capnfabs** [comment]
Hey @ADeeds, I'm actually not able to reproduce this issue on Hugo v0.74.3/extended. What version are you using?

**Comment by ADeeds** [comment]
Sorry for the slow response, but I no longer see this issue on the latest version of the theme. Thanks so much!
