### ISSUE TITLE
3 Questions: LazyLoad, Related Content & Search

### ISSUE THREAD

**Issue by hiensarahly** [capnfabs/paperesque#11]
Hi, thanks for making this theme—I am digging your blog! 

This may seem too much to ask all in one place, but I’m going to try... hope you can shed some light on it:

- Do you support lazyloading for images?
- What do you think about a Related Posts section after a post ends? and...
- Any plans for a search bar?

Thanks! :)

**Comment by capnfabs** [comment]
Hi @hiensarahly!

My answers to your questions are mostly "no" or "not supported by the theme", but you're absolutely welcome to fork the theme and change these things yourself! Some specifics below in case it's helpful:

> - Do you support lazyloading for images?

No, the theme doesn't. I'd consider modifying the `fitfigure` shortcode to add or support `loading=lazy`, and would maybe add a JS poly/ponyfill for it, but wouldn't personally go further than that.

> - What do you think about a Related Posts section after a post ends? and...

I have no plans to build this, but I _have_ been thinking that it would be nice to have something vaguely "call to action"-y. Like a link to an email signup or something. I don't think I'd build a related-posts thing for this myself, but this is [supported by Hugo](https://gohugo.io/content-management/related/).

> -Any plans for a search bar?

Nope, none :) There's some info on [how to do that here](https://gohugo.io/tools/search/) if you're interested in building something like that.
