### ISSUE TITLE
Theme broken since 0.78.1

### ISSUE THREAD

**Issue by capnfabs** [capnfabs/paperesque#12]
Debugging and discussion on [Discourse](https://discourse.gohugo.io/t/js-build-resolve-behaviour-changes-in-0-78-1/30265/3)

**Comment by hieu6** [comment]
hello @capnfabs ! is the entire theme still broken? it's quite lovely :)

**Comment by capnfabs** [comment]
Hey @hieu6! I fixed this a week or two after and forgot to close the bug 😅 Should be working fine now, but let me know if you run into any problems!
