### ISSUE TITLE
SEO improvement?

### ISSUE THREAD

**Issue by iamjoewoods** [capnfabs/paperesque#4]
Hello,
I wanted to know if these two are possible.
1) SEO improvement
2) Adding a move to top button
3) Adding a customizable footer

**Comment by capnfabs** [comment]
Hey @iamjoewoods,

Sorry for the delay -- just realised my notifications have been off for a long time 😅

What do you mean by (1) SEO improvement? I'm not having any problems with the theme from an SEO perspective personally, but I can look into it if you've got more info about the specific problem.

Re (2) and (3): I'm not interested in adding these for my own purposes at the moment, but if you want them, you're definitely welcome to fork the theme and make changes yourself (as per this in the [README](https://github.com/capnfabs/paperesque#git-subtree-easiest)).

I'll change the name of this issue to just reflect the SEO issue.

**Comment by iamjoewoods** [comment]
From the top of my head the two things that are perhaps most important for sharing are [Open Graph ](https://gohugo.io/templates/internal/#open-graph)and Twitter metadata. 

About modifying the theme:
I have never used the subtree command and I am getting an error when I am trying to follow it.
This is on a new site:
![mintty_Jh2AJQqj2F](https://user-images.githubusercontent.com/65498304/85007365-0b7b2380-b179-11ea-87cb-f3f3d6ff2d40.png)

**Comment by capnfabs** [comment]
Hey @iamjoewoods, I'm pretty sure that both Open Graph and Twitter metadata are in there -- at least, I've tested the [home page](https://themes.gohugo.io/theme/paperesque/) and [an article](https://themes.gohugo.io//theme/paperesque/posts/wood-swallow/) from the example site, and both seem to be detected successfully.

I've tested with:

- The [twitter card validator](https://cards-dev.twitter.com/validator)
- [OpenGraphCheck](https://opengraphcheck.com) for FB's Open Graph.

Are you seeing different results or things that aren't displaying correctly?

FWIW, you won't get a featured image unless:
- You add an `images` tag to the front matter for the page, in which case, the first image is used
- You add an image to the Page Bundle that contains 'feature', 'cover', or 'thumbnail' in the filename.

The source for that is in [`feature_image.html`](https://github.com/capnfabs/paperesque/blob/mainline/layouts/partials/feature_image.html). I can't remember if I copied this design from Hugo's default implementations or from another theme.

Regarding making modifications, I was able to reproduce your issue. Here's what I did:

```shell
hugo new site paperesque-test
cd paperesque-test
git init .
git subtree add --prefix themes/paperesque https://github.com/capnfabs/paperesque mainline --squash
```

This gave me the same error:
```
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Working tree has modifications.  Cannot add.
```

The solution is to make sure any outstanding changes to the repo are committed, i.e.

```
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	archetypes/
	config.toml

$ git add . && git commit -am "Init"
[master (root-commit) 9f20669] Init
 2 files changed, 9 insertions(+)
 create mode 100644 archetypes/default.md
 create mode 100644 config.toml
```

Then when you run the subtree command again, it should work:
```
 git subtree add --prefix themes/paperesque https://github.com/capnfabs/paperesque mainline --squash
git fetch https://github.com/capnfabs/paperesque mainline
warning: no common commits
remote: Enumerating objects: 219, done.
remote: Counting objects: 100% (219/219), done.
remote: Compressing objects: 100% (149/149), done.
remote: Total 219 (delta 87), reused 180 (delta 53), pack-reused 0
Receiving objects: 100% (219/219), 1.17 MiB | 2.63 MiB/s, done.
Resolving deltas: 100% (87/87), done.
From https://github.com/capnfabs/paperesque
 * branch            mainline   -> FETCH_HEAD
Added dir 'themes/paperesque'
```

Let me know if you're still having trouble with the subtree stuff, and if you have any more questions or comments to the topic of SEO / Social Media integration.

**Comment by capnfabs** [comment]
Closing; feel free to reopen if you've got more issues / questions!

**Comment by capnfabs** [comment]
FYI @iamjoewoods, I'm doing some work now to support a customisable footer (I want to add email subscriptions to my personal site and need it myself 😊)
