### ISSUE TITLE
Added `[[params.menu]]` as per readme but front page is blank still

### ISSUE THREAD

**Issue by nikitavoloboev** [capnfabs/paperesque#6]
I created new hugo project with `hugo new site ..`. Then made commit as otherwise `git subtree add --prefix themes/paperesque https://github.com/capnfabs/paperesque master --squash` would complain.

I then added

```
[[params.menu]]
  name = "blog"
  url = "posts/"

[[params.menu]]
  name = "about"
  url = "about/"
```

In `config.toml` and ran `hugo server -D`. I got:

```bash
❯ hugo server -D
Building sites … WARN 2020/06/09 10:00:04 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/06/09 10:00:04 found no layout file for "HTML" for kind "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/06/09 10:00:04 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN  
-------------------+-----
  Pages            |  3  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 2 ms
Watching for changes in /Users/nikivi/src/personal/new-nikitavoloboev.xyz/{archetypes,content,data,layouts,static}
Watching for config changes in /Users/nikivi/src/personal/new-nikitavoloboev.xyz/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
WARN 2020/06/09 10:00:14 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

Bunch of warnings but I suppose those are ok. The webpage is still blank though:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/6391776/84122801-496d9e80-aa39-11ea-9697-8213c6d58d1d.png">

I am not sure what I'm missing. I reread the readme again. Thank you for any help.

**Comment by nikitavoloboev** [comment]
It would be very amazing if https://capnfabs.net was open source too, I couldn't find any instances of people using this theme in open source sadly 😞

**Comment by capnfabs** [comment]
Hey @nikitavoloboev, it looks like the theme's not configured correctly, you also need to set `theme = "paperesque"` in your `config.toml`. The warnings from Hugo are what's giving me that hint :)

There's an example in the [`exampleSite` directory in this repo](https://github.com/capnfabs/paperesque/tree/master/exampleSite).

I think you're right that it would be good if the source to my blog was open source too; I turned it off at some point because I didn't want people reading my extremely half-baked drafts before I was ready to publish them 😅

I'm hoping that solves your problem -- please feel free to re-open the issue here if you're still having problems after trying this. I think I'll update the README to make this clearer, too!

**Comment by nikitavoloboev** [comment]
> I didn't want people reading my extremely half-baked drafts before I was ready to publish them

Can't you put the drafts in a dir that is git ignored? :)

**Comment by capnfabs** [comment]
lol. Yes, I can, and do! And they sit there for a while, until I think "ahhhhh i don't want to lose this 3000 word draft that I'll never finish".

btw, here's the update to the docs: https://github.com/capnfabs/paperesque#select-the-theme-in-your-configtoml

**Comment by nikitavoloboev** [comment]
awesome that worked, thx
