### ISSUE TITLE
How to: Port the floating footnotes feature to another theme

### ISSUE THREAD

**Issue by capnfabs** [capnfabs/paperesque#7]
[Charlie Harry Smith asks](https://twitter.com/charliehrysmith/status/1282368956909715457):

> Do you think transplanting them into another theme would be doable for someone with minimal coding experience like me?

**Comment by capnfabs** [comment]
It shouldn't be too hard, but:

- you'll need to modify your theme. I'm not including instructions for this; I believe you've done that already before maybe (but I'm not sure!)
- you'll need to deal with some javascript packaging stuff. This is fiddlier, but I have instructions for this.

I *think* these instructions will get you a fair way but please feel free to follow up if they don't work. Hugo has a pretty steep learning curve in my opinion, so if you've managed it so far, it's more a question of how much time you're willing to spend on it rather than if you can do it or not :) This will be *fiddly*, though.

The general approach I'll take here is to get you to modify the JS in the Paperesque theme, use the build process for Paperesque but tell the build tool to output to your theme :)

0. Clone the paperesque theme
0. Open the file `js/floatingFootnotes.js`
0. Modify the three variables on lines 4-6. They are:
    - `ARTICLE_CONTENT_SELECTOR`: this is dependent on your theme; it's a CSS selector for the main text on an article in your theme. From inspecting [your website](http://www.chsmith.co.uk/), I think it would be `.content .post article>div` but `.content .post article` would probably work too! The theme you're using doesn't use many [CSS classes](https://blog.hubspot.com/website/what-is-css-class) (they're not only useful for styling -- also for identifying parts of the file in scripts!) so this feels to me like it could have unintended side-effects elsewhere in the blog. Check carefully for that; if you run into problems, it's an easy fix, but will require modifying your theme further.
    - `FOOTNOTE_SECTION_SELECTOR`: this is where the footnotes are placed by Hugo. I *think* this is standard across all hugo themes, but that it depends on the version of Hugo you're using? Either way, start by leaving it.
    -  `FLOATING_FOOTNOTE_MIN_WIDTH`: this one's up to you! What's the minimum width you want before footnotes are moved to the side, in pixels?

0. Now you need to add some CSS to your theme so that the footnotes get positioned correctly when they move.
    - The [CSS is here](https://github.com/capnfabs/paperesque/blob/ea54a557f1383e4334245ed8d1e06d89d659af17/static/css/style.css#L517-L532)
    - You might also need to add some styling for that CSS selector you used in `ARTICLE_CONTENT_SELECTOR` above. Maybe something like this:
        ```css
        .content .post article>div {
            position: relative;
        }
        ```
        I have something similar in my theme, and I suspect it's for this, but I have no idea if it's required or not.
    - Whether the CSS works out of the box or not is strongly theme-dependent -- you might have to fiddle with it to make it work.

Now, you have to actually build + import the JS:

- There's instructions [here on how to build](https://github.com/capnfabs/paperesque#hacking--modifying-the-theme). Follow those instructions to get set up.
- Now open `js/main.js` and change it to this:
    ```js
    import enableFloatingFootnotes from "./floatingFootnotes.js";
    enableFloatingFootnotes();
    ```
    We're deleting the other feature from the JS code so that you don't automatically get that feature included.
- Now, run the `parcel` commands from the build instructions again, but instead of using `--out-dir static/js`, run `--out-dir [path-in-your-hugo-site-somewhere]`.
- Now you need to link that in to your hugo theme, by including the file we just built with a <script> tag.

I *think* that's a comprehensive list of instructions, but a lot of those steps hide complexity / assume that you've done certain things before! Hopefully these instructions can at least help you figure out if you're feeling up to it or not :)

**Comment by charlieharrysmith** [comment]
Hi Fabian, thanks again for putting so much effort into these instructions. 

You're right that I've modified my theme and bungled my way through getting Hugo setup and running, but I really do not have much ability or training when it comes to more complex webdev stuff like this. Your help is very much appreciated as a result! 

Nonetheless, I've been making progress today actually trying to get this implemented. So far so good with the CSS bits. But building the JS is proving to be highly problematic! I've got yarn globally installed, but am repeatedly getting this issue when trying to update it in my local paperesque project-specific install:

`➤ YN0009: │ deasync@npm:0.1.19 couldn't be built successfully`

Any ideas what might be causing this? I've made sure I'm running the most recent version of yarn but can't figure out why it keeps struggling with this dependency...

I can't seem to run the `parcel` command until this works, so I'm a bit stuck for now!

Many thanks, Charlie

**Comment by capnfabs** [comment]
Hey Charlie, I tried this today on a clean install of OSX and it's working for me, which means that there's probably something complicated in a build dependency somewhere. It sounds like you just installed yarn for this task, so I'm guessing your version of yarn is up to date, but could you try also checking your version of node/npm?

For me:
```
$ npm --version
6.14.6
$ node --version
v12.18.3
$ yarn --version
1.22.4
```

(This is on OSX El Capitan 10.11.6).

How did you install NodeJS? And which OS are you using?

Having said that, [this from the `deasync` installation guide looks like it's probably the culprit](https://github.com/abbr/deasync#installation):

> Except on a few platforms + Node version combinations where binary distribution is included, DeAsync uses node-gyp to compile C++ source code so you may need the compilers listed in node-gyp. You may also need to update npm's bundled node-gyp.

That is a lot of jargon, but if you click through to the docs, there's instructions. This part is unfortunately OS-specific so it's hard to give meaningful advice on this, but I'd wager that it's either that bit about updating the internal `node-gyp` version or there's otherwise some build dependencies that are missing on your computer.

Good luck! JS toolchains are also something I don't have much experience with, but we'll see if we can't get to the bottom of it.

**Comment by capnfabs** [comment]
This is more of a note-to-self than a note-to-you: it also looks as if all this JS toolchain stuff is included in Hugo by default now as at 0.74. I'll take a look next week sometime and see if it's worth porting some of the JS stuff to Hugo's toolchain to make hacking on this stuff easier in future.

**Comment by capnfabs** [comment]
Ahhh this new JS toolchain stuff is *great*, it means that with a modern enough version of Hugo, you don't need to install a JS toolchain. I'll write some new instructions for how to borrow this floating footnotes thing using the new version of Hugo sometime next week.

**Comment by capnfabs** [comment]
Ok! No need to mess around with toolchains anymore 🎉

Here's some updated instructions (I've copied them from above, but figured it was simpler to just rewrite them than to state what's changed):

1. Update your Hugo version to latest! This might cause _other_ problems with your theme though; a big one that I remember was the switch to Goldmark and needing to explicitly turn _on_ being able to include HTML in content markdown files (search 'unsafe' in the [docs here](https://gohugo.io/getting-started/configuration-markup#goldmark)).
1. Copy everything from paperesque's `assets/js` into a folder called `assets/js` in your theme
1. Open `js/main.js` and change it to this:
    ```js
    import enableFloatingFootnotes from "./floatingFootnotes.js";
    enableFloatingFootnotes();
    ```
    We're deleting the other feature from the JS code so that you don't automatically get that feature included.
1. Open the file js/floatingFootnotes.js
1. Modify the three variables on lines 4-6. They are:
    - `ARTICLE_CONTENT_SELECTOR`: this is dependent on your theme; it's a CSS selector for the main text on an article in your theme. From inspecting [your website](http://www.chsmith.co.uk/), I think it would be `.content .post article>div` but `.content .post article` would probably work too! The theme you're using doesn't use many [CSS classes](https://blog.hubspot.com/website/what-is-css-class) (they're not only useful for styling -- also for identifying parts of the file in scripts!) so this feels to me like it could have unintended side-effects elsewhere in the blog. Check carefully for that; if you run into problems, it's an easy fix, but will require modifying your theme further.
    - `FOOTNOTE_SECTION_SELECTOR`: this is where the footnotes are placed by Hugo. I *think* this is standard across all hugo themes, but that it depends on the version of Hugo you're using? Either way, start by leaving it.
    -  `FLOATING_FOOTNOTE_MIN_WIDTH`: this one's up to you! What's the minimum width you want before footnotes are moved to the side, in pixels?

1. Now you need to add some CSS to your theme so that the footnotes get positioned correctly when they move.
    - The [CSS is here](https://github.com/capnfabs/paperesque/blob/ea54a557f1383e4334245ed8d1e06d89d659af17/static/css/style.css#L517-L532)
    - You might also need to add some styling for that CSS selector you used in `ARTICLE_CONTENT_SELECTOR` above. Maybe something like this:
        ```css
        .content .post article>div {
            position: relative;
        }
        ```
        I have something similar in my theme, and I suspect it's for this, but I have no idea if it's required or not.
    - Whether the CSS works out of the box or not is strongly theme-dependent -- you might have to fiddle with it to make it (a) work (b) look good for your site :)

1. Link and build the JS from within your article. Add these lines to `layouts/_default/baseof.html` near the "custom js" part (around line 109):
   ```
    {{ $opts := dict "targetPath" "js/main.js" "minify" true "target" "es2015" }}
    {{ $mainJs := resources.Get "js/main.js" | js.Build $opts }}
    <script type="text/javascript" src="{{ $mainJs.RelPermalink }}" defer></script>
   ```

   (the first two lines tell Hugo to build the JS, the third line includes the JS in the HTML)

That should be it! The version upgrade to the latest Hugo might cause problems, but it's worth keeping on top of anyway, I think.

**Comment by demonstrandomblog** [comment]
I'm trying to get this working with [book](https://themes.gohugo.io/hugo-book/) theme. Any thoughts? How do I determine ARTICLE_CONTENT_SELECTOR (would it be "body" in my case?)

**Comment by capnfabs** [comment]
Wow, that's a really nice theme! I think it's _probably_ `article.markdown`, but I've only looked into this briefly. It's the part of the page that contains the entire article text, but it's better to choose the most specific part of the HTML for this where possible (i.e. choosing `body` might work, but could also have some side effects re: the rest of your theme, especially because you also need to add CSS for the same selector).

If you're using the table of contents feature in that theme, you might run into problems with the footnotes conflicting! Let me know how you get on.

**Comment by capnfabs** [comment]
Closing this because it only exists for documentation purposes.
